---
format: gfm
---

```{r}
#| label: setup
#| echo: false
library(knitr)
```

<!-- 
Beginning of semester prep: 

- hide all PAs by setting eval=F below
- Remove misc directory from commit history and add back (in .gitignore) 
  when appropriate
-->

# programming_assignments

## Programming assignments for Data Science for Linguistics.

```{r}
#| label: print-links
#| echo: false 
#| results: 'asis'

# Automate TOC
# - After each PA is assigned, update list_elements[X]
# - Reknit after update and push to github

# Get list of folders in current directory
pas <- dir(path = "./staging", pattern = "*.md")

# remove .md
list_elements <- substr(pas, start = 1, stop = max(nchar(pas)) - 3)

# Use pa file names for link references
link_names <- paste0('[', list_elements[1:5], ']')

#
# Get section ref for link
#

# initialize vector
link_ref <- vector(mode = 'character', length = length(link_names))

# store assignment number
for (element in 1:length(link_names)) {

  link_ref[element] <- paste0("(#assignment-", element, ")")

}

# Combine everything into an unordered list
cat(paste0('- ', link_names[1:5], link_ref[1:5], '\n'))
```


---


```{r}
#| label: pa1
#| child: './staging/pa1.md' 
#| eval: true
```

```{r}
#| label: pa2
#| child: './staging/pa2.md' 
#| eval: true
```

```{r}
#| label: pa3
#| child: './staging/pa3.md' 
#| eval: true
```

```{r}
#| label: pa4
#| child: './staging/pa4.md' 
#| eval: true
```

```{r}
#| label: pa5
#| child: './staging/pa5.md'
#| eval: true
```


[w2015]: https://nhorton.people.amherst.edu/mererenovation/17_Wickham.PDF
[R4DS]: http://r4ds.had.co.nz/index.html
[githubtut]: https://www.ds4ling.jvcasillas.com/misc/tutorials/github_setup/
[pa4_fricatives]: https://github.com/ds4ling/programming_assignments/raw/master/misc/data/pa_4_data/fricatives.zip
[pa5_ratings]: https://github.com/ds4ling/programming_assignments/raw/master/misc/data/ratings/ratings_data_2025-04-23.csv


