---
title: "Programming assignment 2"
author: "Joselyn Rodriguez"
date: "Last update: 2021-02-04 09:39:43"
output:
  github_document:
  highlight: kate
  keep_md: yes
  theme: united
---

```{r loading packages}
library(tidyverse)
library(languageR)
```

# Assignment 

You must use 3 of the aforementioned datasets (a different dataset for each plot). All plots must include informative x-, y-axis labels and a title. The plots you must create are:

### familiarize with datasets

```{r}
# some quick looks at the data

summary(beginningReaders)
# head(beginningReaders)
summary(danish)
# head(danish)
summary(dativeSimplified)
# head(dativeSimplified)
summary(english)
# head(english)
summary(spanishFunctionWords)
# head(spanishFunctionWords)
```


### making plots 
 1. A bivariate scatterplot
 
```{r bivariate}

# looking at response times across word frequencies. You'd assume the response times would get shorter as frequency increases and it looks to be the case
bivariate_plot <- danish %>% 
                        ggplot(aes(x = LogWordFreq, y = LogRT)) +
                        geom_point(position = position_jitter(w = 0.1, h = 0.1)) + # jitter a bit horizontally and vertically to see all the points
                        geom_smooth(method = "lm") + # add this in to see the general trend
                        labs(title = "Log Response Times of Word Frequencies",  x = "Log Word Frequency", y = "Log Response Time")
```

 2. A boxplot with different fill colors
 
```{r boxplot}

# this is a graph is a bit crowded, but it shows the subjects' log response times and reading score 
fill_colors_plot <- beginningReaders %>% 
                        ggplot(aes(x = Subject, y = LogRT, fill = ReadingScore)) +
                        geom_boxplot() +
                        theme(axis.text.x = element_text(angle = 90, hjust = 1, size = 5)) +
                        labs(title = "Log Response Time by Subject", y = "Log Response Time")
```
 
 3. A plot of your choice that includes a stat_summary and a facet.


```{r statsummary}

# graph of the log response time for different word categories faceted across age. It doesn't look like there's a difference
stat_sum_plot <- english %>%
                        ggplot(aes(x = WordCategory, y = RTnaming)) +
                        geom_point(alpha = 0.3, position = position_jitter(w = 0.3, h = 0.1)) + # also jittered this a bit
                        stat_summary(color = "red", fun.data = mean_sdl, geom = "pointrange") +
                        facet_grid( ~ AgeSubject) +
                        labs(title = "Log Response Time for Word Categories by Age", x = "Word Category", y = "Log Response Time")
```

