---
title: "Programming assignment 2"
author: "Jessica Varela"
date: "Last update: `r Sys.Date()`"
output: 
  github_document:
  highlight: kate
  keep_md: yes 
  theme: united 
---

```{r setup, include=FALSE}
library(tidyverse)
library(languageR)
```


## Including Plots

You can also embed plots, for example:

```{r}
ggplot(data = danish) + geom_point(mapping = aes(x = ResidFamSize, y = ResidSemRating), color = "purple") + xlab("Family size") + ylab("Sem Rating") + ggtitle("Scatterplot of Residualized Family Size and Sem Rating")

ggplot(data = english, aes(x = WrittenFrequency, y = WrittenSpokenFrequencyRatio, fill = WordCategory)) + geom_boxplot() + xlab("Written Frequency") + ylab("Written Spoken Frequency Ratio") + ggtitle("Boxplot of the distribution of written
frequency and ratio") + scale_fill_brewer(palette="YlOrRd")

ggplot(data = dativeSimplified) + stat_summary(mapping = aes(x = RealizationOfRec, y = LengthOfTheme), fun.min = min, fun.max = max, fun = median) + geom_point(data = dativeSimplified, aes(x = RealizationOfRec, y = LengthOfTheme), alpha = .1, color = "blue") + facet_wrap(~ AnimacyOfRec, nrow = 1)  + xlab("Realization of Rec") + ylab("Length of Theme") + ggtitle("Length of Time categorized by realization of Rec broken down by animacy")



```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
