---
title: "Programming assignment 2"
author: "Kyle Parrish"
date: "Last update: 2021-02-04 09:39:43"
output:
github_document:
highlight: kate
keep_md: yes
theme: united
---

```{r}

# Load libraries 
library(languageR)
library(tidyverse)

# assign dfs to objects to familiarize myself
beginningReaders = beginningReaders
danish = danish
dativeSimplified = dativeSimplified
english = english 
spanishFunctionWords = spanishFunctionWords

```

```{r}

#bivariate plot

ggplot(data = english, aes(x = Familiarity, y = WrittenFrequency, color = WordCategory)) + geom_point(alpha = .1) + geom_smooth(method = "lm", color = "grey35") + xlab("Familiarity") + ylab("Written Frequency") + ggtitle("Word familiarity and Written Frequency from English data")


#boxplot

ggplot(data = english, aes(x = WrittenFrequency, y = RTnaming, fill = AgeSubject)) + geom_boxplot() + xlab("Written Frequency") + ylab("Reaction time") + ggtitle("A box plot by age of the distribution of wrtitten frequency and reaction time")
                                                                                                                                                                  
#plot with stat summary and facet

ggplot(data = english) + stat_summary(mapping = aes(x = WordCategory, y = RTnaming), fun.min = min, fun.max = max, fun = median) + geom_jitter(data = english, aes(x = WordCategory, y = RTnaming), alpha = .1, color = "seagreen3") + facet_wrap(~ AgeSubject, nrow = 1)  + xlab("Word Category") + ylab("Reaction time") + ggtitle("Reaction times of word classes by age")


```
