---
title: "Programming assignment 2"
author: Stephanie Rodriguez
date: "2023-02-11"
output: 
    github_document: 
    highlight: 
    keep_md: yes
    theme: united
---

```{r, load-packages}
library("tidyverse")
library("languageR")
```

```{r, load-data}
beginningReaders = beginningReaders
danish = danish 
dativeSimplified = dativeSimplified
english = english 
spanishFunctionWords = spanishFunctionWords
```

```{r, english}
view(english)
```

```{r, ggplot-for-english}
english %>%
ggplot(aes(x = Familiarity, y = RTnaming)) + 
  geom_point() +
  labs(x = "The familiarity of subjective ratings", y = "The RT of word naming", title = "Word naming by familiarity")
```
```{r, ggplot-for-danish}
danish %>%
  ggplot(aes(x = Affix, y = LogRT, fill = Sex)) +
  geom_boxplot() +
    labs(x = "The affixes in the words", y = "The RT of response latency", title = "The RT of response latency of affixes")
```

```{r, dativeSimplified}
view(dativeSimplified)
```

```{r, ggplot-for-dativeSimplified}
 dativeSimplified %>%
  ggplot(aes(x = AnimacyOfRec, y = LengthOfTheme)) +
   stat_summary(fun.data = mean_se, geom = "pointrange", 
               pch = 21, fill = "white") +
  facet_grid(. ~ AnimacyOfTheme)
```




















