---
title: "Programming assignment 2"
author: "Chaoyi Chen"
date: "Last update: 2021-02-07 23:09:45"
output:
  github_document:
  highlight: kate
  keep_md: yes
  theme: united
---

**i. A bivariate scatterplot**

```{r}
library(tidyverse)
library(languageR)
beginningReaders %>%
  ggplot(aes(x = LogFrequency, y = LogRT), size = 0.1) + # The original size of dots seems to be too big, so I found a code on the Internet to make it smaller.
  labs(title = "beginningReaders-word frequency and reaction time") + # I didn't find any part of the book about adding a title to a plot, so I found it on the internet
  geom_point()
```


**ii. A boxplot with different fill colors**
```{r}
danish %>%
  ggplot(aes(x = Subject, y = LogRT, fill = Subject)) +
  labs(title = "danish-reaction time among subjects") +
  geom_boxplot()
```

**iii. A plot of your choice that includes a `stat_summary` and a facet.**


```{r}
english %>%
  ggplot(aes(x = WordCategory, y = RTlexdec)) +
  labs(title = "english-wordcategory and reaction time") +
  geom_boxplot() +
  facet_wrap(~AgeSubject) +
  stat_summary(mapping = aes(x = WordCategory, y = RTlexdec),fun.min = min, fun.max = max, fun = median)
```



