---
title: "Programming assignment 2"
author: "Jiawei Shao"
date: "Last updated `r format(Sys.time(), '%Y-%m-%d %X')`"
output:
  github_document:
  lighlight: kate
  keep_md: yes
  theme: united
---

```{r, 'plot 1 bivariate scatterplot'}

# A bivariate scatterplot
library(languageR)
library(tidyverse)
beginningReaders %>% 
  ggplot() +
    aes(x = LogRT, y = ReadingScore ) + 
      geom_jitter() +
        labs(x = "LogRT", y = "ReadingScore", title = "beginningReaders-ReadingScore as a function of LogRT")

```


```{r, 'plot 2 boxplot with different fill colors'}

# A boxplot with different fill colors
library(languageR)
library(tidyverse)
  danish %>% 
  ggplot() +
    aes(x = Sex, y = LogRT, fill = Sex ) + 
      geom_boxplot() +
        labs(x = "Sex", y = "LogRT", title = "danish-LogRT as a function of Sex")

```


```{r, 'plot of choice'}

# A plot of your choice that includes a stat_summary and a facet.
library(languageR)
library(tidyverse)
  english %>% 
    ggplot() +
    aes(x = AgeSubject, y = CorrectLexdec, color = AgeSubject) + 
    geom_jitter(alpha = 0.3) +
    stat_summary(fun.data = mean_se, color = "black", geom = "pointrange") +
    facet_grid (WordCategory ~ .)+
    labs(x = "AgeSubject", y = "CorrectLexdec", 
         caption = "Mean +/- SE", title = "english-SE of CorrectLexdec comparison bewteen age groups")

```

