---
title: "Programming assignment 2"  
author: "Jorge Vargas"  
date: "Last update: `r Sys.time()`"  
output:  
  html_document:  
    highlight: kate  
    keep_md: yes  
    theme: united
---

```{r}
library(languageR)
library(tidyverse)
glimpse(danish)  
glimpse(english)
glimpse(spanishFunctionWords)
glimpse(dativeSimplified)
glimpse(beginningReaders)
```


# 1. Scatter plot: Beginning Readers

```{r}
beginningReaders |>
  ggplot() +
  aes(x = LogFrequency, y = ProportionOfErrors) +  
  stat_summary(fun="mean", geom="point")+
  labs(x = "Log Frequency", y = "Proportion of errors", title = "Log Frequency and proportion of errors") + 
  theme_minimal()  

```


#2. Boxplot: English


```{r}
english$AgeSubject <- as.factor(english$AgeSubject)
```

```{r}
english |>  
  ggplot() +  
  (aes(x = AgeSubject, y = RTnaming, fill = AgeSubject)) +  
  geom_boxplot(outlier.shape = 21, outlier.color = "black", outlier.fill = "white") +  
  scale_fill_manual(values = c("young" = "green", "old" = "purple")) +  
  labs(x = "Age group", y = "RT naming", title = "RT per age group") +  
  theme_minimal()
```


#3. Point range: Danish
```{r}
danish |>
  ggplot() +
  aes(x = Affix, y = LogRT) + 
  facet_grid(. ~ Sex) +
  stat_summary(fun.data ="mean_sdl", geom= "pointrange") +  
  labs(x = "Affix", y = "Log Reaction Time", title = "Reaction Times per Affix") + 
  theme_minimal()  

```








